apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app_environment_id: 567041dc-08ea-41e0-a19b-b3585daa53ac
    env_id: e4869bab-0957-4bf1-89f6-40145e6d1429
    env_name: lasanaa
    organization_id: 8b881a3f-0c62-4ca4-ab9a-db66a32ed28c
    platformer_app_id: b68a624a-8246-4012-94e8-3b2d1f15eb28
    platformer_app_name: mamama
    platformer_component: rudder
    platformer_system: "true"
    project_id: 306c7793-1f94-4221-a91c-46e5e233ebe8
  name: mamama
  namespace: okay
spec:
  replicas: 1
  selector:
    matchLabels:
      app_environment_id: 567041dc-08ea-41e0-a19b-b3585daa53ac
      env_id: e4869bab-0957-4bf1-89f6-40145e6d1429
      env_name: lasanaa
      organization_id: 8b881a3f-0c62-4ca4-ab9a-db66a32ed28c
      platformer_app_id: b68a624a-8246-4012-94e8-3b2d1f15eb28
      platformer_app_name: mamama
      platformer_component: rudder
      platformer_system: "true"
      project_id: 306c7793-1f94-4221-a91c-46e5e233ebe8
  strategy: {}
  template:
    metadata:
      annotations:
        platformer.com/reload-hash: d1e29c9c-7ff3-440c-8d7a-21ccc24c6f5a
      labels:
        app_environment_id: 567041dc-08ea-41e0-a19b-b3585daa53ac
        env_id: e4869bab-0957-4bf1-89f6-40145e6d1429
        env_name: lasanaa
        organization_id: 8b881a3f-0c62-4ca4-ab9a-db66a32ed28c
        platformer_app_id: b68a624a-8246-4012-94e8-3b2d1f15eb28
        platformer_app_name: mamama
        platformer_component: rudder
        platformer_system: "true"
        project_id: 306c7793-1f94-4221-a91c-46e5e233ebe8
    spec:
      imagePullSecrets:
      - name: reg-mamama-3192360657
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
